MyFirstDjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'

urlpatterns=[
 #   url(r'^$',views.index,name='index'),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesViews.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^search/$',views.search,name='search'),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name='comments'
urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags

# Create your models here.
@python_2_unicode_compatible
class Category(models.Model):
    name=models.CharField(max_length=100)

@python_2_unicode_compatible
class Tag(models.Model):
    name=models.CharField(max_length=100)

@python_2_unicode_compatible
class Post(models.Model):
    title=models.CharField(max_length=70)
    body=models.TextField()
    created_time=models.DateTimeField()
    modified_time=models.DateTimeField()
    excerpt=models.CharField(max_length=200,blank=True)

    category=models.ForeignKey(Category)
    tags=models.ManyToManyField(Tag,blank=True)
    author=models.ForeignKey(User)

    #新增views字段记录阅读量
    views=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    #增加模型方法
    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])

    #自动生成文章摘要
    def save(self,*args,**kwargs):
        #如果没有填写摘要
        if not self.excerpt:
            #首先实例化一个markdown类，用于渲染body的文本
            md=markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt=strip_tags(md.convert(self.body))[:54]

            #调用父类的save方法将数据保存到数据库中
        super(Post,self).save(*args,**kwargs)

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=225)
    url=models.URLField(blank=True)
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)

    post=models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name','email','url','text']

blog/views.py
from django.shortcuts import render
from .models import Post,Category
from django.shortcuts import render,get_object_or_404
import markdown
from comments.forms import CommentForm
from django.db.models.aggregates import Count
from django.views.generic import ListView,DetailView

from django.http import HttpResponse
# Create your views here.

"""def index(requst):
    post_list=Post.objects.all().order_by('-created_time')
    return render(requst,'blog/index.html',context={
        'post_list':post_list
    })
"""
#把视图函数改写为类函数，以减少视图函数重复代码，节省开发时间
class IndexView(ListView):
    model = Post #将model指定为Post,获取Post模型
    template_name = 'blog/index.html' #指定渲染的模板
    context_object_name = 'post_list' #指定获取的模型列表数据保存的变量名，这个变量会传递给模板

'''
def detail(requst,pk):
    post=get_object_or_404(Post,pk=pk)

    #阅读量+1
    post.increase_views()

    post.body=markdown.markdown(post.body,
                                extensions=[
                                    'markdown.extensions.extra',
                                    'markdown.extensions.codehilite',
                                    'markdown.extensions.toc'
                                ])
    form=CommentForm()
    comment_list=post.comment_set.all()
    context={'post':post,
             'form':form,
             'comment_list':comment_list}
    return  render(requst,'blog/detail.html',context=context)
'''
class PostDetailView(DetailView):
    #这些属性和ListView是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        #覆写get方法的原因是因为每当文章被访问一次，就得将文章访问数+1
        #get方法返回的是一个HTTPresponse实例
        #之所以先要调用父类的get方法，是因为只有当get方法调用后
        #才有self.object属性，其值为Post模型实例，即被访问的文章post
        response=super(PostDetailView,self).get(request,*args,*kwargs)

        #将文章浏览数+1
        #注意self.object的值就是被访问的文章post
        self.object.increase_views()

        #视图必须返回一个httpresponse对象
        return response

    def get_object(self, queryset=None):
        #覆写get_object的目的是因为需要对post的body值进行渲染
        post=super(PostDetailView,self).get_object(queryset=None)
        post.body=markdown.markdown(post.body,
                                    extensions=[
                                        'markdown.extensions.extra',
                                        'markdown.extensions.codehilite',
                                        'markdown.extensions.toc',
                                    ])
        return post

    def get_context_data(self, **kwargs):
        #覆写get_context_data的目的是因为除了将post的值传递给模板外（DetailView已经帮我们完成）
        #还要把评论表单、post下的评论列表传递给模板
        context=super(PostDetailView,self).get_context_data(**kwargs)
        form=CommentForm()
        comment_list=self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list,
        })
        return context
class CategoryView(IndexView):
    def get_queryset(self):#get_queryset()方法默认获取指定模型的全部列表数据
        cate=get_object_or_404(Category,pk=self.kwargs.get('pk'))
        #在类视图中，从 URL 捕获的命名组参数值保存在实例的 kwargs 属性（是一个字典）里，
        # 非命名组参数值保存在实例的 args 属性（是一个列表）里。
        return super(CategoryView, self).get_queryset().filter(category=cate)
'''
def archives(request,year,month):
    post_list=Post.objects.filter(created_time__year=year,
                                  created_time__month=month).order_by('-created_time')
    return render(request,'blog/index.html',context={
        'post_list':post_list
    })
'''
class ArchivesViews(IndexView):
    def get_queryset(self):
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super(ArchivesViews,self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month).order_by('-created_time')
'''def category(request,pk):
    cate=get_object_or_404(Category,pk=pk)
    # category_list=Category.objects.annotate(num_posts=Count('post'))
    post_list=Post.objects.filter(category=cate).order_by('-created_time')
    return render(request,'blog/index.html',context={'post_list':post_list,
                                                     })
'''
def search(request):
    q=request.GET.get('q')
    error_msg=''

    if not q:
        error_msg='请输入关键词'
        return render(request,'blog/index.html',{'error_msg':error_msg,
                                                  })
    post_list=Post.objects.filter(title__icontains=q)
    return render(request,'blog/index.html',{'error_msg':error_msg,
                                               'post_list':post_list,
                                             })

comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from .models import Comment
from .forms import CommentForm
# Create your views here.

def post_comment(request,post_pk):
    post=get_object_or_404(Post,pk=post_pk)

    if request.method == 'POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect(post)

        else:
            comment_list=post.comment_set.all()
            context={'post':post,
                     'form':form,
                     'comment_list':comment_list
                     }
            return render(request,'blog/detail.html',context=context)
    return redirect(post)

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Wing &amp; House</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        {% load blog_tags %}

	    <!-- css -->
        <link rel="shortcut icon" href="{% static 'blog/img/bitbug_favicon.ico' %}" >
<!--		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
-->
        <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
<!--	<script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
使用CDN加快bootstrap和jQuery的加载速度
-->
        <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Wing</b> &amp; House</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="blog/index.html" data-hover="Home">首页</a></li>
    								<li class="cl-effect-11"><a href="blog/full-width.html" data-hover="Blog">博客</a></li>
    								<li class="cl-effect-11"><a href="blog/about.html" data-hover="About">关于</a></li>
    								<li class="cl-effect-11"><a href="blog/contact.html" data-hover="Contact">联系</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                                    {% csrf_token %}
									<input type="search" name='q' placeholder="搜索" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >Templates</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
                        {% block main %}
                        {% endblock main %}
                    </main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">最新文章</h3>
                            {% get_recent_posts as recent_post_list %}
							<ul>
                                {% for post in recent_post_list %}
								<li>
									<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
								</li>
                                {% empty %}
                                暂无文章！
                                {% endfor %}
							</ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">归档</h3>
                            {% archives as date_list %}
							<ul>
                                {% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
								</li>
                                {% empty %}
                                暂无归档
                                {% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">分类</h3>
                            {% get_categories as category_list %}
							<ul>
                                {% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}({{ category.num_posts }})</a>
								</li>
                                {% empty %}
                                暂无分类！
                                {% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com -More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">HOME</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">Templates</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="blog/index.html">Home</a></li>
					<li><a href="blog/full-width.html">Blog</a></li>
					<li><a href="blog/about.html">About</a></li>
					<li><a href="blog/contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>

                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                <span class="post-author"><a href="#">{{ post.author }}</a></span>

                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>

                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <hr>
    <section class="comment-area">
        <!-- UY BEGIN -->
        <div id="uyan_frame"></div>
        <script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js"></script>
        <!-- UY END -->
    </section>
    <ul class="comment-list list-unstyled">
        {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <span>|</span>
            <span class="submit-date">{{ comment.created_time }}</span>
            <div class="text">
                {{ comment.text }}
            </div>
        </li>
    {% empty %}
    暂无评论
    {% endfor %}
    </ul>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">URL:</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>

                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                <span class="post-author"><a href="#">{{ post.author }}</a></span>

                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>

                <span class="views-count"><a href="{{ post.get_absolute_url }}}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p> {{ post.excerpt }}...</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读<span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}

templates/blog/results.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <div>
        在这里显示文章的相应信息
        </div>
    {% empty %}
        <div class="no-post">
        没有搜索到符合条件的文章
        </div>
    {% endfor %}
{% endblock %}